# Generated by Django 4.0.2 on 2022-07-07 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=100)),
                ('anoPublicacao', models.IntegerField()),
                ('isbn', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField(default='')),
                ('serieAlvo', models.CharField(blank=True, choices=[('1ano', ' 1ano'), ('2ano', '2ano'), ('3ano', '3ano')], max_length=8)),
                ('imagem', models.ImageField(blank=True, upload_to='img_livro')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livros.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Livros Didáticos',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_back', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Disponivel'), ('a', 'Agendado'), ('s', 'Solicitado'), ('e', 'Emprestado')], default='d', help_text='Situação do Livro', max_length=1)),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='livros.livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MeusLivros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
            },
        ),
    ]
