# Generated by Django 4.0.2 on 2022-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_emprestimos_delete_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
